### ISSUE TITLE
Zsh を使っていると 環境変数 USERNAME が PCにログインしている USERNAME になってしまう

### ISSUE THREAD

**Issue by t0yohei** [tunagohan/trello_add_week#1]
README 通りに実行しようとしたら下記のエラーが出た。

```
[trello_add_week]  ruby provisioning/get_lane_id.rb  
Traceback (most recent call last):
	5: from provisioning/get_lane_id.rb:5:in `<main>'
	4: from /trello_add_week/lib/board_id.rb:26:in `get'
	3: from /trello_add_week/lib/board_id.rb:52:in `get'
	2: from /trello_add_week/lib/board_id.rb:57:in `parse_body'
	1: from /.rbenv/versions/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/.rbenv/versions/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at 'model not found' (JSON::ParserError)
```

デバックしてみると。下記のURLでAPIを叩きに行っているっぽい。 USERNAME の部分が、 direnv で設定したものに下記変わってないっぽい。
- 正: t0yohei ( `export USERNAME=` で指定したもの)
- 今回: pcのユーザー名

```
[trello_add_week]  ruby provisioning/get_lane_id.rb  
"https://trello.com/1/members/&{pcのユーザー名}/boards?key=${key}&token=${token}&fields=name"
```

どうやら、 zsh の場合 USERNAME は PC にログイン中のユーザーID が入ってしまうらしい。
https://qiita.com/quenhulu/items/61edc5dffa711b08d64c

`USERNAME` を使用せずに、別のもので置き換えてあげるとかがいいかなーと思ったのですがどうでしょうか？？ 🤔 

fish にしましょう、でも済む話ですがw

**Comment by tunagohan** [comment]
修正します( ✌︎'ω')✌︎

**Comment by tunagohan** [comment]
@t0yohei 
Fixed a proposed issue :)
Thanks, 

https://github.com/tunagohan/trello_add_week/pull/2
